name: 'Playwright E2E tests'
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
jobs:
  playwright-e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
      - name: install
        run: |
          yarn install
      - name: test
        run: |
          yarn playwright-e2e:test
