name: 'Storybook Visual'
on: push
# on:
#   push:
#     branches:
#       - main
jobs:
  storybook-visual:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./storefront
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: yarn
      - name: Build Storybook
        run: yarn run storybook-build --quiet
      - name: Percy Test
        run: yarn run storybook-visual
