name: 'API Tests'
on: push
env:
  NODE_ENV: test
jobs:
  api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '20.x'
      - run: yarn
      - run: yarn backend:test
